config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('contact/', include('contact.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import contact_view

urlpatterns = [
    path('', contact_view, name='contact'),
]

posts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home_view, name='home'),
    path('single/<slug:slug>/', single_post_view, name='single'),
    path('about/', about_view, name='about'),
    path('fashion/', fashion_view, name='fashion'),
    path('travel/', travel_view, name='travel'),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()

    def __str__(self):
        return self.name

posts/models.py
from django.db import models

# Create your models here.

TYPE = (
    (0, 'FASHION'),
    (1, 'TRAVEL'),
)


class Tag(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return self.tag


class Category(models.Model):
    category = models.CharField(max_length=255)

    def __str__(self):
        return self.category


def post_image_path(instance, filename):
    return f'posts/{instance.get_type_display()}/{filename}'


class Post(models.Model):
    title = models.CharField(max_length=255)
    type = models.IntegerField(choices=TYPE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField()
    image = models.ImageField(upload_to=post_image_path)
    content = models.TextField()
    tag = models.ManyToManyField(Tag, blank=True)
    created_at = models.DateField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    avatar = models.ImageField(upload_to='comments')
    website = models.URLField(null=True, blank=True)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

posts/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['post']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

contact/views.py
from django.shortcuts import render
from .forms import ContactForm

# Create your views here.
from .models import Contact


def contact_view(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
    obj = Contact.objects.order_by('-id')
    context = {
        'form': form,
        'objects': obj
    }

    return render(request, 'contact/contact.html', context)

posts/views.py
from django.shortcuts import render
from .models import Post, Comment, Tag, Category


def home_view(request):
    objects = Post.objects.order_by('-id')
    comments = Comment.objects.all()
    categories = Category.objects.all()
    q = request.GET.get('q')
    cat = request.GET.get('cat')
    tags = Tag.objects.all()
    tag = request.GET.get('tag')

    if tag:
        objects = objects.filter(tag__tag__exact=tag)
    if cat:
        objects = objects.filter(category__category__exact=cat)
    if q:
        objects = objects.filter(title__icontains=q)
    context = {
        'objects': objects,
        'comments': comments,
        'categories': categories,
        'tags': tags
    }
    return render(request, 'posts/index.html', context)


def last_3_posts_view(request):
    obj = Post.objects.order_by('-id')[:3]
    tags = Tag.objects.all()
    category = Category.objects.all()
    context = {
        'objects': obj,
        'tags': tags,
        'categories': category
    }
    return render(request, 'rside.html', context)


def single_post_view(request, slug):
    obj = Post.objects.get(slug=slug)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    context = {
        'object': obj,
        'tags': tags,
        'categories': categories
    }
    return render(request, 'posts/single.html', context)


def about_view(request):
    return render(request, 'posts/about.html')


def fashion_view(request):
    articles = Post.objects.order_by('-id').filter(type=0)

    context = {
        'objects': articles
    }
    return render(request, 'posts/fashion.html', context)


def travel_view(request):
    articles = Post.objects.order_by('-id').filter(type=1)

    context = {
        'objects': articles
    }
    return render(request, 'posts/fashion.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Andera</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&amp;display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script nonce="5295d087-18c0-461e-929e-2c3e8ee45a80">(function (w, d) {
        !function (a, e, t, r) {
            a.zarazData = a.zarazData || {}, a.zarazData.executed = [], a.zaraz = {deferred: []}, a.zaraz.q = [], a.zaraz._f = function (e) {
                return function () {
                    var t = Array.prototype.slice.call(arguments);
                    a.zaraz.q.push({m: e, a: t})
                }
            };
            for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e);
            a.addEventListener("DOMContentLoaded", (() => {
                var t = e.getElementsByTagName(r)[0], z = e.createElement(r),
                    n = e.getElementsByTagName("title")[0];
                for (a.zarazData.c = e.cookie, n && (a.zarazData.t = e.getElementsByTagName("title")[0].text), a.zarazData.w = a.screen.width, a.zarazData.h = a.screen.height, a.zarazData.j = a.innerHeight, a.zarazData.e = a.innerWidth, a.zarazData.l = a.location.href, a.zarazData.r = e.referrer, a.zarazData.k = a.screen.colorDepth, a.zarazData.n = e.characterSet, a.zarazData.o = (new Date).getTimezoneOffset(), a.zarazData.q = []; a.zaraz.q.length;) {
                    const e = a.zaraz.q.shift();
                    a.zarazData.q.push(e)
                }
                z.defer = !0, z.referrerPolicy = "origin", z.src = "../../cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData))), t.parentNode.insertBefore(z, t)
            }))
        }(w, d, 0, "script");
    })(window, document);</script>

</head>
<body>

<div id="colorlib-page">
    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
    {% include 'sidebar.html' %}
    {% block content %}

    {% endblock %}
   </div>


    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js%2bpopper.min.js%2bbootstrap.min.js.pagespeed.jc.ufA-InWYhU.js' %}"></script>
    <script>eval(mod_pagespeed_j9z0BOW3Xo);</script>
    <script>eval(mod_pagespeed_Sv59xs6XfY);</script>
    <script>eval(mod_pagespeed_6hivBMilT4);</script>
    <script src="{% static 'js/jquery.easing.1.3.js%2bjquery.waypoints.min.js%2bjquery.stellar.min.js%2bowl.carousel.min.js.pagespeed.jc.7Uf8nwPPt3.js' %}"></script>
    <script>eval(mod_pagespeed_a9in6ca9LP);</script>
    <script>eval(mod_pagespeed_E5Rl_eUdra);</script>
    <script>eval(mod_pagespeed_J7fR9gg3IV);</script>
    <script>eval(mod_pagespeed_JGC9XV$UWo);</script>
    <script src="{% static 'js/jquery.magnific-popup.min.js%2baos.js%2bjquery.animateNumber.min.js%2bscrollax.min.js%2bgoogle-map.js%2bmain.js.pagespeed.jc.noK85cOv9x.js' %}"></script>
    <script>eval(mod_pagespeed_9FDixMCPbL);</script>
    <script>eval(mod_pagespeed_cWDp1F0K9O);</script>
    <script>eval(mod_pagespeed_tBed9FYmsP);</script>
    <script>eval(mod_pagespeed_xipmmYMCNr);</script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
    <script>eval(mod_pagespeed_YuUFcjXVeT);</script>
    <script>eval(mod_pagespeed_6pY$MsZg3C);</script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
    <script defer
            src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
            integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
            data-cf-beacon='{"rayId":"6fccc2540930fe3c","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.12.0","si":100}'
            crossorigin="anonymous"></script>
</body>
</html>

templates/contact/contact.html
{% extends 'base.html' %}
{% block content %}
    <div id="colorlib-main">
        <section class="ftco-section contact-section px-md-4">
            <div class="container">
                <div class="row d-flex mb-5 contact-info">
                    <div class="col-md-12 mb-4">
                        <h2 class="h3">Contact Information</h2>
                    </div>
                    <div class="w-100"></div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Address:</span> Tashkent, Mirzo Ulug'bek, 54-A</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Phone:</span> <a href="tel://998998826060">📞 +99899 882- 60-60 </a></p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Email:</span> <a
                                    href=<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2996.2777146282806!2d69.3228385158627!3d41.32457407926991!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38aef572e5842f55%3A0xa87fc261e04f75ea!2siSystem%20IT%20academy!5e0!3m2!1sru!2s!4v1650624019483!5m2!1sru!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>><span
                                    class="__cf_email__" data-cfemail="d9b0b7bfb699a0b6acabaab0adbcf7bab6b4">[email&#160;protected]</span></a>
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Website</span> <a href="#">isystem.uz</a></p>
                        </div>
                    </div>
                </div>
                <div class="row block-9">
                    <div class="col-lg-6 d-flex">
                        <form method="post" class="bg-light p-5 contact-form">
                            {% csrf_token %}
                            <div class="form-group">
<!--                                <input type="text" class="form-control" placeholder="Your Name">-->
                                {{ form.name }}
                            </div>
                            <div class="form-group">
<!--                                <input type="text" class="form-control" placeholder="Your Email">-->
                                {{ form.email }}
                            </div>
                            <div class="form-group">
<!--                                <input type="text" class="form-control" placeholder="Subject">-->
                                {{ form.subject }}
                            </div>
                            <div class="form-group">
<!--                                <textarea name="" id="" cols="30" rows="7" class="form-control"-->
<!--                                          placeholder="Message"></textarea>-->
                                {{ form.message }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-6 d-flex">
                        <div class="bg-light"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2996.2777146282806!2d69.3228385158627!3d41.32457407926991!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38aef572e5842f55%3A0xa87fc261e04f75ea!2siSystem%20IT%20academy!5e0!3m2!1sru!2s!4v1650624019483!5m2!1sru!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/pagination.html
<div class="row">
    <div class="col text-center text-md-left">
        <div class="block-27">
            <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
            </ul>
        </div>
    </div>
</div>

templates/posts/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <div id="colorlib-main">
            <section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
                <div class="container-fluid px-0">
                    <div class="row d-flex">
                        <div class="col-md-6 d-flex">
                            <div class="img d-flex align-self-stretch align-items-center js-fullheight"
                                 style="background-image:url({% static 'images/myphoto.png' %})">
                            </div>
                        </div>
                        <div class="col-md-6 d-flex align-items-center">
                            <div class="text px-4 pt-5 pt-md-0 px-md-4 pr-md-5 ftco-animate">
                                <h2 class="mb-4">I'm <span>Alimardon Boqijonov</span> a FullStack Web Developer &amp; SMM Specialist</h2>
                                <p>Uzbekiston, Tashkent. Islamic, Musilman. I like BMW and Lamborghini URUS. "Team A & i" asoschisi. 2002-yil 12-fevralda Farg'onada tug'ilgan</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>

{% endblock %}

templates/posts/fashion.html
{% extends 'base.html' %}
{% block content %}
    <div id="colorlib-main">
        <section class="ftco-section">
            <div class="container">
                <div class="row px-md-4">
                    {%  for object in objects %}
                         <div class="col-md-12">
                        <div class="blog-entry ftco-animate d-md-flex">
                            <a href="single.html" class="img img-2"
                               style="background-image:url({{ object.image.url }})"></a>
                            <div class="text text-2 pl-md-4">
                                <h3 class="mb-2"><a href="{% url 'single' object.slug %} ">{{ object.title }}</a></h3>
                                <div class="meta-wrap">
                                    <p class="meta">
                                        <span><i class="icon-calendar mr-2"></i>{{ object.created_at }}</span>
                                        <span><a href="{% url 'single' object.slug %}"><i class="icon-folder-o mr-2"></i>{{ object.category }}</a></span>
                                        <span><i class="icon-comment2 mr-2"></i>{{ object.comment }}</span>
                                    </p>
                                </div>
                                <p class="mb-4">{{ object.content }}</p>
                                <p><a href="{% url 'single' object.slug %}" class="btn-custom">Read More <span class="ion-ios-arrow-forward"></span></a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% include 'pagination.html' %}
            </div>
        </section>
    </div>


<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-xl-8 py-5 px-md-5">
                        <div class="row pt-md-4">
                            {% for object in objects %}
                                <div class="col-md-12">
                                    <div class="blog-entry ftco-animate d-md-flex">
                                        <a href="{% url 'single' object.slug %}" class="img img-2"
                                           style=" background-image:url({{ object.image.url }})"></a>
                                        <div class="text text-2 pl-md-4">
                                            <h3 class="mb-2"><a href="{% url 'single' object.slug %}">{{ object.title }}</a></h3>
                                            <div class="meta-wrap">
                                                <p class="meta">
                                                    <span><i
                                                            class="icon-calendar mr-2"></i>{{ object.created_at }}</span>
                                                    <span><a href="{% url 'single' object.slug %}"><i
                                                            class="icon-folder-o mr-2"></i>{{ object.category }}</a></span>
                                                    <span><i class="icon-comment2 mr-2"></i>{{ object.comment_set.count }} Comments</span>
                                                </p>
                                            </div>
                                            <p class="mb-4">{{ object.content }}</p>
                                            <p>
                                            <ul class="tagcloud">

                                                {% for tag in object.tag.all %}
                                                    <a href="?tag={{ tag.tag }}"
                                                       class="tag-cloud-link">{{ tag.tag }}</a>
                                                {% endfor %}
                                            </ul>


                                            </p>
                                            <p><a href="{% url 'single' object.slug %}" class="btn-custom">Read More
                                                <span
                                                        class="ion-ios-arrow-forward"></span></a></p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                        {% include 'pagination.html' %}
                    </div>
                    <div class="col-xl-4 sidebar ftco-animate bg-light pt-5">
                        {% include 'rside.html' with categories=categories tags=tags %}
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00"/>
        </svg>
    </div>
{% endblock %}

templates/posts/single.html
{% extends 'base.html' %}

{% block content %}
    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-lg-8 px-md-5 py-5">
                        <div class="row pt-md-4">
                            <h1 class="mb-3">{{ object.title}}</h1>
                            <p><img src="{{ object.image.url }}" alt="" class="img-fluid"></p>
                            <p>{{ object.content }}</p>
                            <div class="tag-widget post-tag-container mb-5 mt-5">
                                <div class="tagcloud">
                                    {% for tag in object.tag.all %}
                                        <a href="#" class="tag-cloud-link">{{ tag }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="pt-5 mt-5">
                                <h3 class="mb-5 font-weight-bold">6 Comments</h3>
                                <ul class="comment-list">
                                    <li class="comment">
                                        <div class="vcard bio">
                                            <img src="images/xperson_1.jpg.pagespeed.ic.P4pHl6glbj.jpg"
                                                 alt="Image placeholder">
                                        </div>
                                        <div class="comment-body">
                                            <h3>John Doe</h3>
                                            <div class="meta">October 03, 2018 at 2:21pm</div>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem
                                                laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat
                                                saepe enim sapiente iste iure! Quam voluptas earum impedit
                                                necessitatibus, nihil?</p>
                                        </div>
                                    </li>
                                </ul>

                                <div class="comment-form-wrap pt-5">
                                    <h3 class="mb-5">Leave a comment</h3>
                                    <form action="#" class="p-3 p-md-5 bg-light">
                                        <div class="form-group">
                                            <label for="name">Name *</label>
                                            <input type="text" class="form-control" id="name">
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Email *</label>
                                            <input type="email" class="form-control" id="email">
                                        </div>
                                        <div class="form-group">
                                            <label for="website">Website</label>
                                            <input type="url" class="form-control" id="website">
                                        </div>
                                        <div class="form-group">
                                            <label for="message">Message</label>
                                            <textarea name="" id="message" cols="30" rows="10"
                                                      class="form-control"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 sidebar ftco-animate bg-light pt-5">
                        {% include 'rside.html' with tags=tags categories=categories%}
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/rside.html
{% load static %}
<div class="sidebar-box pt-md-4">
    <form action="#" class="search-form">
        <div class="form-group">
            <span class="icon icon-search"></span>
            <input name = 'q' type="search" class="form-control" placeholder="Type a keyword and hit enter">
        </div>
    </form>
</div>
<div class="sidebar-box ftco-animate">
    <h3 class="sidebar-heading">Categories</h3>
    <ul class="categories">
        {% for category in categories %}
            <li><a href="?cat={{ category }}">{{ category.category }} <span>{{ category.post_set.count }}</span></a></li>
        {% endfor %}
    </ul>
</div>
<div class="sidebar-box ftco-animate">
    <h3 class="sidebar-heading">Popular Articles</h3>
    {% for object in objects|slice:':3' %}
        <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4"
               style="background-image:url({{ object.image.url }})"></a>
            <div class="text">
                <h3 class="heading"><a href="{% url 'single' object.slug %}">{{ object.title }}</a></h3>
                <div class="meta">
                    <div><a href="#"><span class="icon-calendar mr-2"></span>{{ object.created_at }}</a></div>
                    <div><a href="#"><span class="icon-folder-o mr-2"></span>{{ object.category }}</a></div>
                    <div><a href="#"><span class="icon-chat mr-2"></span>{{ object.comment_set.count }}</a></div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<div class="sidebar-box ftco-animate">
    <h3 class="sidebar-heading">Tag Cloud</h3>
    <ul class="tagcloud">
        {% for tag in tags %}
            <a href="?tag={{ tag.tag }}" class="tag-cloud-link">{{ tag.tag }}</a>
        {% endfor %}
    </ul>
</div>
<div class="sidebar-box subs-wrap img"
     style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.yyDakF8d8Y.jpg' %})">
    <div class="overlay"></div>
    <h3 class="mb-4 sidebar-heading">Newsletter</h3>
    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia</p>
    <form action="#" class="subscribe-form">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Email Address">
            <input type="submit" value="Subscribe" class="mt-2 btn btn-white submit">
        </div>
    </form>
</div>
<div class="sidebar-box ftco-animate">
    <h3 class="sidebar-heading">Archives</h3>
    <ul class="categories">
        <li><a href="#">December 2018 <span>(10)</span></a></li>
        <li><a href="#">September 2018 <span>(6)</span></a></li>
        <li><a href="#">August 2018 <span>(8)</span></a></li>
        <li><a href="#">July 2018 <span>(2)</span></a></li>
        <li><a href="#">June 2018 <span>(7)</span></a></li>
        <li><a href="#">May 2018 <span>(5)</span></a></li>
    </ul>
</div>
<div class="sidebar-box ftco-animate">
    <h3 class="sidebar-heading">Paragraph</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
        necessitatibus voluptate quod mollitia delectus aut.</p>
</div>

templates/sidebar.html
{% load static %}
        <aside id="colorlib-aside" role="complementary" class="js-fullheight">
            <nav id="colorlib-main-menu" role="navigation">
                <ul>
                    <li class="colorlib-active"><a href="/">Home</a></li>
                    <li><a href="/fashion/">Fashion</a></li>
                    <li><a href="/travel/">Travel</a></li>
                    <li><a href="/about/">About</a></li>
                    <li><a href="/contact/">Contact</a></li>
                </ul>
            </nav>
            <div class="colorlib-footer">
                <h1 id="colorlib-logo" class="mb-4"><a href="index-2.html" style="background-image:url({% static 'images/myphoto.png' %})">Alimardon
                    <span>Software Enginner</span></a></h1>
                <div class="mb-4">
                    <h3>Subscribe for newsletter</h3>
                    <form action="#" class="colorlib-subscribe-form">
                        <div class="form-group d-flex">
                            <div class="icon"><span class="icon-paper-plane"></span></div>
                            <input type="text" class="form-control" placeholder="Enter Email Address">
                        </div>
                    </form>
                </div>
                <p class="pfooter">
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a
                        href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </aside>